/**
 * Phase 0 verification — CyberSlots foundation check.
 *
 * Proves the full ACP link against the official kimi CLI *before* any app
 * code is built on top of it:
 *
 *   1. Generates an isolated KIMI_CODE_HOME (config.toml from .dev/secrets.json —
 *      never committed) so the user's real ~/.kimi-code is untouched.
 *   2. Spawns `kimi acp` and drives it via @agentclientprotocol/sdk:
 *      initialize → capability dump → session/new → session/prompt.
 *   3. Streams every session update to the console, records the observed
 *      event surface, then tries switching the session model to MiniMax
 *      and prompting again (non-fatal if unsupported).
 *   4. Writes a machine-readable report to .dev/phase0-report.json.
 *
 * Usage: node scripts/phase0-verify.mjs [--skip-minimax]
 */

import { spawn } from 'node:child_process';
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Readable, Writable } from 'node:stream';

import { ClientSideConnection, ndJsonStream } from '@agentclientprotocol/sdk';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const DEV_DIR = join(ROOT, '.dev');
const KIMI_HOME = join(DEV_DIR, 'kimi-home');
const WORK_DIR = join(DEV_DIR, 'workdir');
const REPORT_PATH = join(DEV_DIR, 'phase0-report.json');
const OVERALL_TIMEOUT_MS = 180_000;
const PROMPT_TIMEOUT_MS = 90_000;

const log = (...a) => console.log('[phase0]', ...a);
const section = (t) => console.log(`\n========== ${t} ==========`);

// Stream teardown after child.kill() surfaces as rejected pending reads in
// the SDK's ndjson loop — harmless during shutdown, fatal any other time.
let shuttingDown = false;
process.on('unhandledRejection', (e) => {
  if (shuttingDown) return;
  console.error('[phase0] unhandledRejection:', e);
  process.exit(1);
});

// ---------------------------------------------------------------- secrets
function loadSecrets() {
  const p = join(DEV_DIR, 'secrets.json');
  if (!existsSync(p)) throw new Error(`missing ${p}`);
  return JSON.parse(readFileSync(p, 'utf8'));
}

// ------------------------------------------------------------ config.toml
function writeKimiConfig(secrets) {
  mkdirSync(KIMI_HOME, { recursive: true });
  mkdirSync(WORK_DIR, { recursive: true });
  // MiniMax is the verified-working provider for now (kimi key pending fix
  // — probe showed 401 on every kimi endpoint), so it drives the fatal leg.
  const toml = `# generated by phase0-verify (contains secrets — .dev/ is gitignored)
default_model = "${secrets.minimax.model}"

[providers.kimi]
type = "openai"
base_url = "${secrets.kimi.baseUrl}"
api_key = "${secrets.kimi.apiKey}"

[providers.minimax]
type = "openai"
base_url = "${secrets.minimax.baseUrl}"
api_key = "${secrets.minimax.apiKey}"

[models."${secrets.kimi.model}"]
provider = "kimi"
model = "${secrets.kimi.model}"
max_context_size = ${secrets.kimi.maxContextSize}

[models."${secrets.minimax.model}"]
provider = "minimax"
model = "${secrets.minimax.model}"
max_context_size = ${secrets.minimax.maxContextSize}
`;
  writeFileSync(join(KIMI_HOME, 'config.toml'), toml, 'utf8');
  log(`config.toml written → ${join(KIMI_HOME, 'config.toml')}`);
}

// ------------------------------------------------------------- spawn kimi
function resolveKimiSpawn() {
  const appData = process.env.APPDATA ?? '';
  const mainMjs = join(appData, 'npm', 'node_modules', '@moonshot-ai', 'kimi-code', 'dist', 'main.mjs');
  if (existsSync(mainMjs)) {
    return { command: process.execPath, args: [mainMjs, 'acp'], label: `node ${mainMjs}` };
  }
  // Fallback: .cmd shim needs a shell on Windows (Node >=20.12 EINVAL fix).
  return { command: 'kimi', args: ['acp'], label: 'kimi acp (PATH)', shell: true };
}

function spawnKimiAcp() {
  const { command, args, label, shell } = resolveKimiSpawn();
  log(`spawning: ${label}`);
  const child = spawn(command, args, {
    cwd: WORK_DIR,
    shell: shell ?? false,
    env: { ...process.env, KIMI_CODE_HOME: KIMI_HOME },
    stdio: ['pipe', 'pipe', 'pipe'],
  });
  child.stderr.setEncoding('utf8');
  child.stderr.on('data', (d) => {
    for (const line of String(d).split(/\r?\n/)) if (line.trim()) console.error('  [kimi:stderr]', line);
  });
  child.on('exit', (code, signal) => log(`kimi exited code=${code} signal=${signal ?? ''}`));
  return child;
}

// --------------------------------------------------------------- ACP client
/** Minimal ACP Client impl: records updates, auto-answers permissions. */
function createClientImpl(state) {
  return {
    async sessionUpdate(n) {
      const u = n.update ?? {};
      const kind = u.sessionUpdate ?? '(unknown)';
      state.updateKinds.add(kind);
      state.updates.push(u);
      switch (kind) {
        case 'agent_message_chunk':
          if (u.content?.type === 'text') process.stdout.write(u.content.text);
          state.gotText = true;
          break;
        case 'agent_thought_chunk':
          state.gotThinking = true;
          break;
        case 'available_commands_update':
          state.slashCommands = (u.availableCommands ?? []).map((c) => c.name);
          break;
        default:
          console.log(`\n  [update:${kind}]`, JSON.stringify(u).slice(0, 300));
      }
    },
    async requestPermission(p) {
      const opts = p.options ?? [];
      const pick = opts.find((o) => /allow/i.test(o.kind ?? '') || /allow/i.test(o.name ?? '')) ?? opts[0];
      log(`requestPermission → auto-answer "${pick?.name ?? pick?.optionId}" (tool: ${p.toolCall?.title ?? '?'})`);
      state.permissionRequests.push(p);
      if (!pick) return { outcome: { outcome: 'cancelled' } };
      return { outcome: { outcome: 'selected', optionId: pick.optionId } };
    },
    async readTextFile() {
      throw new Error('fs capability disabled in phase0');
    },
    async writeTextFile() {
      throw new Error('fs capability disabled in phase0');
    },
  };
}

function withTimeout(promise, ms, tag) {
  let timer;
  const timeout = new Promise((_, reject) => {
    timer = setTimeout(() => reject(new Error(`${tag} timed out after ${ms}ms`)), ms);
  });
  return Promise.race([promise, timeout]).finally(() => clearTimeout(timer));
}

// --------------------------------------------------------------------- main
async function main() {
  const skipMinimax = process.argv.includes('--skip-minimax');
  const secrets = loadSecrets();
  writeKimiConfig(secrets);

  const child = spawnKimiAcp();
  const state = {
    updateKinds: new Set(),
    updates: [],
    permissionRequests: [],
    slashCommands: [],
    gotText: false,
    gotThinking: false,
  };
  const report = { startedAt: new Date().toISOString(), steps: {} };

  const finish = (ok, error) => {
    shuttingDown = true;
    report.ok = ok;
    if (error) report.error = String(error?.stack ?? error);
    report.observedUpdateKinds = [...state.updateKinds];
    report.slashCommands = state.slashCommands;
    report.finishedAt = new Date().toISOString();
    writeFileSync(REPORT_PATH, JSON.stringify(report, null, 2), 'utf8');
    log(`report → ${REPORT_PATH}`);
    try { child.kill(); } catch { /* already dead */ }
    // Give the child a moment to die, then hard-exit.
    setTimeout(() => process.exit(ok ? 0 : 1), 500).unref();
  };

  try {
    const stream = ndJsonStream(Writable.toWeb(child.stdin), Readable.toWeb(child.stdout));
    const client = new ClientSideConnection(() => createClientImpl(state), stream);

    // ---- 1. initialize
    section('1. initialize');
    const init = await withTimeout(
      client.initialize({
        protocolVersion: 1,
        clientCapabilities: { fs: { readTextFile: false, writeTextFile: false } },
      }),
      20_000,
      'initialize',
    );
    console.log(JSON.stringify(init, null, 2));
    report.steps.initialize = init;

    // ---- 2. session/new
    section('2. session/new');
    const sess = await withTimeout(
      client.newSession({ cwd: WORK_DIR, mcpServers: [] }),
      30_000,
      'session/new',
    );
    console.log(JSON.stringify(sess, null, 2));
    report.steps.newSession = sess;
    const sessionId = sess.sessionId;

    // ---- 3. prompt on default model (minimax — verified upstream)
    section(`3. session/prompt (${secrets.minimax.model})`);
    const t0 = Date.now();
    const res1 = await withTimeout(
      client.prompt({
        sessionId,
        prompt: [{ type: 'text', text: '请用一句话介绍你自己，并明确说出你的模型名称。' }],
      }),
      PROMPT_TIMEOUT_MS,
      'prompt(minimax)',
    );
    console.log(`\n  → stopReason=${res1.stopReason} in ${Date.now() - t0}ms`);
    report.steps.promptMinimax = { stopReason: res1.stopReason, ms: Date.now() - t0, gotText: state.gotText };
    if (!state.gotText) throw new Error('minimax prompt produced no text chunks');

    // ---- 4. switch model → kimi, prompt again (non-fatal until key is fixed)
    if (!skipMinimax) {
      section(`4. setSessionModel → ${secrets.kimi.model} + prompt (kimi key check)`);
      try {
        await client.unstable_setSessionModel({ sessionId, modelId: secrets.kimi.model });
        state.gotText = false;
        const t1 = Date.now();
        const res2 = await withTimeout(
          client.prompt({
            sessionId,
            prompt: [{ type: 'text', text: 'One short sentence: what model are you?' }],
          }),
          PROMPT_TIMEOUT_MS,
          'prompt(kimi)',
        );
        console.log(`\n  → stopReason=${res2.stopReason} in ${Date.now() - t1}ms`);
        report.steps.promptKimi = { stopReason: res2.stopReason, ms: Date.now() - t1, gotText: state.gotText };
      } catch (e) {
        console.error('  kimi leg failed (non-fatal, key pending fix):', e?.message ?? e);
        report.steps.promptKimi = { error: String(e?.message ?? e) };
      }
    }

    // ---- summary
    section('SUMMARY');
    log('observed update kinds:', [...state.updateKinds].join(', ') || '(none)');
    log('slash commands:', state.slashCommands.join(', ') || '(none)');
    log('thinking chunks seen:', state.gotThinking);
    log('permission requests:', state.permissionRequests.length);
    finish(true);
  } catch (err) {
    console.error('\n[phase0] FAILED:', err);
    finish(false, err);
  }
}

const killTimer = setTimeout(() => {
  console.error(`[phase0] overall timeout ${OVERALL_TIMEOUT_MS}ms — aborting`);
  process.exit(2);
}, OVERALL_TIMEOUT_MS);
killTimer.unref();

main();
